image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore AspNetCoreProtobufFormatters.sln
  - dotnet restore SystemTests.sln
build_script:
- dotnet build AspNetCoreProtobufFormatters.sln
- dotnet build SystemTests.sln
before_build:
- appveyor-retry dotnet restore AspNetCoreProtobufFormatters.sln -v Minimal
