image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - ps: Install-Product node $env:nodejs_version
  - dotnet --version
  - dotnet restore AspNetCoreProtobufFormatters.sln
  - dotnet restore SystemTests.sln
  - choco install googlechrome
build_script:
- dotnet build AspNetCoreProtobufFormatters.sln
- dotnet build SystemTests.sln
before_build:
- appveyor-retry dotnet restore AspNetCoreProtobufFormatters.sln -v Minimal
